# -*- coding: utf-8 -*-
"""语音报时台词/歌词库：经典电影台词与歌词（中英文）。

纯数据模块，零依赖（不引入 Qt / edge_tts），供纯逻辑层 voice_chime.py
按 8 小时周期分批轮换选取（周期序号决定当前批次，批次内按报时次序轮换取不同
条目）。新增条目无需登记配置，追加到列表即可（批次由库长度自动均分）。
"""
from __future__ import annotations

# 中文台词/歌词：经典电影中文名句与华语歌词（尽量短，适合语音播报）。
CHINESE_QUOTES: tuple[str, ...] = (
    "生活就像一盒巧克力，你永远不知道下一颗是什么味道。",
    "曾经有一份真诚的爱情放在我面前，我没有珍惜。",
    "做人如果没有梦想，那和咸鱼有什么分别？",
    "能力越大，责任越大。",
    "明天，又是新的一天。",
    "所有的相遇，都是久别重逢。",
    "人生没有彩排，每一天都是现场直播。",
    "每一个不曾起舞的日子，都是对生命的辜负。",
    "不要放弃，永远不要放弃。",
    "山重水复疑无路，柳暗花明又一村。",
    "千里之行，始于足下。",
    "心若向阳，无畏悲伤。",
    "你若安好，便是晴天。",
    "世界那么大，我想去看看。",
    "岁月不居，时节如流。",
    "长路奉献给远方，玫瑰奉献给爱情。",
    "越过山丘，虽然已白了头。",
    "时间是让人猝不及防的东西，晴时有风阴有时雨。",
    "如果全世界我也可以放弃，至少还有你值得我去珍惜。",
    "没有什么能够阻挡，你对自由的向往。",
    "我曾经跨过山和大海，也穿过人山人海。",
    "最初的梦想，紧握在手上。",
    "想飞上天，和太阳肩并肩。",
    "我和我最后的倔强，握紧双手绝对不放。",
    "夜空中最亮的星，能否听清。",
    "海阔天空，在勇敢以后。",
    "把每天当成是末日来相爱。",
    "慢慢喜欢你，慢慢的亲密。",
    "回忆像个说书的人，用充满乡音的口吻。",
    "不要愁老之将至，你老了一定很可爱。",
    "人生天地间，忽如远行客。",
    "真正的勇气，是知道生活的真相后依然热爱生活。",
    "有些事现在不做，一辈子都不会做了。",
    "人生就像一场戏，因为有缘才相聚。",
    "你若不离不弃，我必生死相依。",
    "愿你走出半生，归来仍是少年。",
    "生活不止眼前的苟且，还有诗和远方。",
    "陪伴是最长情的告白。",
    "最好的时光，就是现在。",
    "每一次告别，都要用力一点。",
)

# 英文台词/歌词：经典电影台词与英文歌词（短句，适合英文音色）。
ENGLISH_QUOTES: tuple[str, ...] = (
    "Life was like a box of chocolates. You never know what you're gonna get.",
    "May the Force be with you.",
    "Carpe diem. Seize the day, boys.",
    "I'm the king of the world!",
    "Houston, we have a problem.",
    "Just keep swimming.",
    "There's no place like home.",
    "Here's looking at you, kid.",
    "I'll be back.",
    "Keep your friends close, but your enemies closer.",
    "With great power comes great responsibility.",
    "It's not who I am underneath, but what I do that defines me.",
    "Why so serious?",
    "Do, or do not. There is no try.",
    "You talking to me?",
    "Frankly, my dear, I don't give a damn.",
    "Go ahead, make my day.",
    "To be or not to be, that is the question.",
    "The stuff that dreams are made of.",
    "May you live in interesting times.",
    "Imagine all the people living life in peace.",
    "Don't stop believin'.",
    "Here comes the sun, and I say it's all right.",
    "Let it be, let it be.",
    "Yesterday, all my troubles seemed so far away.",
    "We are the champions, my friends.",
    "I will always love you.",
    "Nothing's gonna change my love for you.",
    "Every breath you take, every move you make.",
    "Sweet dreams are made of this.",
    "Wake me up when September ends.",
    "All you need is love.",
    "Let it go, let it go.",
    "I see the light.",
    "The greatest thing you'll ever learn is just to love and be loved in return.",
    "You had me at hello.",
    "Love means never having to say you're sorry.",
    "Some people are worth melting for.",
    "The sea, once it casts its spell, holds one in its net of wonder forever.",
    "Not all those who wander are lost.",
)
